# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

stages:
- stage: Continous_Integration
  displayName: Continous Integration
  pool:
     vmImage: ubuntu-latest

  jobs:
    - job: ContinousIntegration
      displayName: Continous Integration

      steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.7'
        displayName: 'Use Python 3.7'

      - script: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        displayName: 'Install dependencies'

      - task: DockerInstaller@0
        inputs:
          dockerVersion: '20.10.13'
          releaseType: stable
      - task: Docker@2
        displayName: Login to Docker Hub
        inputs:
          command: 'build'
          Dockerfile: '**/Dockerfile'
        
      - task: CopyFiles@2
        inputs:
          SourceFolder: '$(Build.SourcesDirectory)'
          Contents: '**'
          TargetFolder: '$(Build.StagingDirectory)'
      - task: Docker@2
        displayName: Push to Docker Hub
        inputs:
          containerRegistry: 'Docker Hub Push'
          repository: 'abhihpes/flask-app-test'
          command: 'push'